<!DOCTYPE bookstore [

<!ELEMENT bookstore (book*)>

<!ELEMENT book (title, author+, year, price)>
<!ATTLIST book 
		category CDATA #REQUIRED
                cover (hardback|paperback) #IMPLIED
>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title lang CDATA "en">
<!--Валидация проходит только в случае lang CDATA "en" или lang CDATA #REQUIRED, но по заданию 6 и 8 должны быть оба эти варианта, поэтому вариант предыдущей строки для полного выполнения обоих заданий такой: <!ATTLIST title lang CDATA "en" #REQUIRED> -->

<!ELEMENT author (#PCDATA)>

<!ELEMENT year (#PCDATA)>

<!ELEMENT price (#PCDATA)>

]>


<bookstore>
  <book category="cooking">
    <title lang="en">Everyday Italian</title>
    <author>Giada De Laurentiis</author>
    <year>2005</year>
    <price>30.00</price>
  </book>
  <book category="children">
    <title lang="en">Harry Potter</title>
    <author>J K. Rowling</author>
    <year>2005</year>
    <price>29.99</price>
  </book>
  <book category="web">
    <title lang="en">XQuery Kick Start</title>
    <author>James McGovern</author>
    <author>Per Bothner</author>
    <author>Kurt Cagle</author>
    <author>James Linn</author>
    <author>Vaidyanathan Nagarajan</author>
    <year>2003</year>
    <price>49.99</price>
  </book>
  <book category="web" cover="paperback">
    <title lang="en">Learning XML</title>
    <author>Erik T. Ray</author>
    <year>2003</year>
    <price>39.95</price>
  </book>
</bookstore>
